services:
  fastapi:
    image: fastapi-app
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
