
services:
  fastapi:
    build:
      context: .
    image: fastapi-app:prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mynetwork

networks:
  mynetwork:
