"""Initial schema

Revision ID: 4ee0864f38b4
Revises: 
Create Date: 2025-09-17 20:52:31.778759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ee0864f38b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_vhodni_podatki_id'), table_name='fastapi_vhodni_podatki')
    op.drop_table('fastapi_vhodni_podatki')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastapi_vhodni_podatki',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('casovna_znacka', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('poraba', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dinamicne_cene', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stranka_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fastapi_vhodni_podatki_pkey'))
    )
    op.create_index(op.f('ix_fastapi_vhodni_podatki_id'), 'fastapi_vhodni_podatki', ['id'], unique=False)
    # ### end Alembic commands ###
