"""Put back fastapi_vhodni_podatki

Revision ID: 636dd10c9da1
Revises: 4ee0864f38b4
Create Date: 2025-09-17 21:10:02.200751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636dd10c9da1'
down_revision: Union[str, Sequence[str], None] = '4ee0864f38b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastapi_vhodni_podatki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('casovna_znacka', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('poraba', sa.Float(), nullable=True),
    sa.Column('dinamicne_cene', sa.Float(), nullable=True),
    sa.Column('stranka_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stranka_id'], ['fastapi_stranke.stranka_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_vhodni_podatki_id'), 'fastapi_vhodni_podatki', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_vhodni_podatki_id'), table_name='fastapi_vhodni_podatki')
    op.drop_table('fastapi_vhodni_podatki')
    # ### end Alembic commands ###
