"""Make stranka fields nullable

Revision ID: b5ac236dbd93
Revises: 636dd10c9da1
Create Date: 2025-09-18 14:17:22.788903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ac236dbd93'
down_revision: Union[str, Sequence[str], None] = '636dd10c9da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fastapi_stranke', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fastapi_stranke', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fastapi_stranke', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fastapi_stranke', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fastapi_stranke', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fastapi_stranke', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
